### ISSUE TITLE
Another similar dotfile manager

### ISSUE THREAD

**Issue by QiangF** [NNBnh/superb-bootstrap#1]
Just for your information:
https://github.com/ssh0/dot

**Comment by NNBnh** [comment]
Sorry for the late reply and thank you for the information you provide.

After looking into  [`ssh0`'s dot](https://github.com/ssh0/dot) i found that other than both mine and ssh0 dotfile manager use shellscript, our dotfile manager don't have much in common:
- [`ssh0`'s dot](https://github.com/ssh0/dot) is a program integrate with `git` to manager dotfile, it come with lots of handy commands to help you manager your dotfile
- [SuperB Bootstrap](https://github.com/NNBnh/superb-bootstrap) is not a program:
  - It's a framework that guides you through managing your dotfile so it can be installed with just one click (or one command).
  - Unlike [`ssh0`'s dot](https://github.com/ssh0/dot), `git` is optional because you can use anything that can download and upload files. You can even install local dotfiles that you transfer from the removable hard drive and don't need `git` at all
