### ISSUE TITLE
Packages are not installed though seem to be configured properly

### ISSUE THREAD

**Issue by weiss-d** [NNBnh/superb-bootstrap#14]
Hi! I'm trying to bootstrap a VM from my laptop. Both run [Hash Linux](hashproject.org/) - Arch-based distro.
My `packagelist` looks like this (I use only `PAC:` and `AUR:` suffixes):

![image](https://user-images.githubusercontent.com/62437174/113327089-2f33e280-9323-11eb-957e-b135d56b1872.png)

`setup` is unchanged.

When I clone the repo to VM and run `./setup`, it makes symlinks but doesn't install any packages. The output is this:

![image](https://user-images.githubusercontent.com/62437174/113326830-de23ee80-9322-11eb-9452-773ed5a5a1e5.png)

**Comment by NNBnh** [comment]
Hello @weiss-d ,Sorry for this inconvenience and thank you for the bug report, this bug is from the [Termux supported](https://github.com/NNBnh/superb-bootstrap/releases/tag/1.7.1) and it's had been [fixed](https://github.com/NNBnh/superb-bootstrap/commit/316e81311aec777e706f8ae131d140adb13ee175).

## The fix:

Please update this block of code from:

https://github.com/NNBnh/superb-bootstrap/blob/e241495c403090d79a83471c8f612cddab0e71d0/setup#L137-L153

to:

https://github.com/NNBnh/superb-bootstrap/blob/316e81311aec777e706f8ae131d140adb13ee175/setup#L137-L155

**Comment by weiss-d** [comment]
Hi @NNBnh !
I've changed these lines in my repo, but result are still the same.

![image](https://user-images.githubusercontent.com/62437174/113387828-bfab0b00-9395-11eb-89a2-776f6e20f077.png)

![image](https://user-images.githubusercontent.com/62437174/113387993-0dc00e80-9396-11eb-91ca-06a64dd48dc0.png)

**Comment by weiss-d** [comment]
The quick'n'dirty workaround now is to replace lines 137-153 with:
```shell
		PACKAGEMANAGER_MAIN='Pacman'
		PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST AUR"
```
