### ISSUE TITLE
More comprehensive way to install PIP?

### ISSUE THREAD

**Issue by weiss-d** [NNBnh/superb-bootstrap#28]
Hi everyone!
Turned out this line will not work in recent versions of Ubuntu (and maybe many other distros), because their system's Python doesn't have the `ensurepip` module. Ubuntu users are forced to install `pip` by this command: `sudo apt-get install python3-pip`.
 
https://github.com/NNBnh/superb-bootstrap/blob/a3b1bdf6c1789246533fb27fcae959c85556281e/sbb#L450

The possible solution is to use [this script](https://github.com/pypa/get-pip) whenever Python says "No module named ensurepip". But it may interfere with the way PIP is meant to be installed by the developers of a particular distro.

What do you say to that?

**Comment by LoricAndre** [comment]
One option would be to open a shell for the user to install pip if this command does not work, then continue when the shell exits

**Comment by NNBnh** [comment]
Hello,

From [this answers](https://stackoverflow.com/questions/6587507/how-to-install-pip-with-python-3):
> ### Python 3.4+ and Python 2.7.9+
>
> Good news! Python 3.4 (released March 2014) ships with Pip. This is the best feature of any Python release. It makes the community's wealth of libraries accessible to everyone. Newbies are no longer excluded by the prohibitive difficulty of setup. In shipping with a package manager, Python joins Ruby, Nodejs, Haskell, Perl, Go--almost every other contemporary language with a majority open-source community. Thank you Python.

Because `pip` only need to be manually install with Python ≤ 2.7.8 and Python ≤ 3.3, for now i will using this as a solution:
https://github.com/NNBnh/superb-bootstrap/blob/4f4aac34565b7338b4f7a6ad451edb46eebc69ff/sbb#L70
https://github.com/NNBnh/superb-bootstrap/blob/4f4aac34565b7338b4f7a6ad451edb46eebc69ff/sbb#L441

Later on i will try to add a `sbb_install_curl` function to download and use [get-pip.py](https://github.com/pypa/get-pip) as @weiss-d suggested.

**Comment by NNBnh** [comment]
Done in [SBB 2.1.0 update](https://github.com/NNBnh/superb-bootstrap/releases/tag/2.1.0)!
